modLoader="javafml"
loaderVersion="[40,)"
license="GNU GPLv3"

[[mods]]
modId="nep"
version="0.4.0"
displayName="Not Enough Powers"
authors="MigaMi"
credits=""
description="Superpowers from your favorite Anime and Videogames!"

[[dependencies.nep]]
    modId="forge"
    mandatory=true
    versionRange="[46, 48)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nep]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20, 1.20.2)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nep]]
    modId="framework"
    mandatory=true
    versionRange="[0.7.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nep]]
    modId="geckolib"
    mandatory=true
    versionRange="[4.4.4,)"
    ordering="NONE"
    side="BOTH"